### ISSUE TITLE
Download bug in blackhole 

### ISSUE THREAD

**Issue by Archonz-crazy** [Sangwan5688/BlackHole#98] opened 2021-08-05 13:07 UTC
**Describe the bug**
The download all button is not working.

**To Reproduce**
1. Go to playlist
2. Click on the download all button
3. It is loading but not doing anything.
4. See error.

**Expected behavior**
The whole playlist should be downloaded.

**Smartphone (please complete the following information):**
 - Device: Samsung m21.
 - OS: Android 11.

**Comment by Sangwan5688** [comment] 2021-08-06 06:25
Can you describe the issue in detail like what was the playlist name, how many songs were downloaded, what it's showing, does any of the songs have any special character in their name, etc.

**Comment by Sangwan5688** [comment] 2021-09-04 11:50
As the issue is not reproducible and I haven't received any other info regarding it from anyone I will be closing it. If anyone face this issue feel free to open it again.

**Closed by Sangwan5688** 2021-09-04 11:50 UTC
