### ISSUE TITLE
Shitt

### ISSUE THREAD

**Issue by abhi101Gh** [Sangwan5688/BlackHole#331] opened 2022-06-03 16:01 UTC
Being from india its asking me to use vpn for indian server seriously????😂

**Comment by Sangwan5688** [comment] 2022-06-03 16:03
Duplicate of #329

**Closed** 2022-06-03 16:02 UTC

**Comment by abhi101Gh** [comment] 2022-06-03 16:05
Because of that the home page is not working?if that's the case I'm sorry bro...i wasn't aware of that ... anyways loved u work😍
