### ISSUE TITLE
Youtube import playlists turning the songs into hindi music

### ISSUE THREAD

**Issue by JoshuaZXL1** [Sangwan5688/BlackHole#298] opened 2022-04-24 02:21 UTC
**Describe the bug**
When I try to import a playlist from youtube it recognizes the music (26 songs) but than it removes 17 of them and turns them into hindi indian music 
**To Reproduce**
3. Do this and that
use the import from youtube playlist on this link https://www.youtube.com/playlist?list=PLD61626F6813F6C5F
**Expected behavior**
Make a normal playlist for me to listen to
**Screenshots**

**Device Details (please complete the following information):**
 - OS: [e.g. Android, Windows, iOS, Linux]
 - Version: [e.g. Android 12, iOS 15, Windows 11 20H2]
 - Device: [e.g. Pixel 4, iPhone 13]
 - App Version [e.g. v1.13.0]

**App Logs**
If possible please provide app logs here.

**Comment by JoshuaZXL1** [comment] 2022-04-24 02:26
Ok its actually incapable of adding anything from youtube that isnt mainstream music to a playlist thats fun

**Comment by JoshuaZXL1** [comment] 2022-04-24 02:31
![Screenshot_20220423-202307](https://user-images.githubusercontent.com/38868718/164953546-e4da58ea-972c-4c9e-9597-fd897eb6eaef.jpg)
![Screenshot_20220423-202323](https://user-images.githubusercontent.com/38868718/164953548-6f752e09-2c51-4cd1-8cd9-db019fea52ec.jpg)
![Screenshot_20220423-202329](https://user-images.githubusercontent.com/38868718/164953550-0e8fe81e-518a-443a-90ee-90123c25317e.jpg)
![Screenshot_20220423-202313](https://user-images.githubusercontent.com/38868718/164953551-eb996f28-f03b-4d6d-a5bb-ac60cc72a551.jpg)
![Screenshot_20220423-202319](https://user-images.githubusercontent.com/38868718/164953552-701f1fd3-921e-4dcf-a8ac-e0177a49739f.jpg)

**Comment by Sangwan5688** [comment] 2022-04-24 05:26
Duplicate of #173

**Closed by Sangwan5688** 2022-04-24 05:26 UTC
Labels: bug

**Comment by Jordan14568** [comment] 2022-05-25 10:33
Bro can you add playlist search by link in youtube section so we can directly add playlist in blackhole app playlist without importing.

**Comment by Jordan14568** [comment] 2022-05-25 10:34
> Duplicate of #173
Bro can you add playlist search by link in youtube section so we can directly add playlist in blackhole app playlist without importing.
