### ISSUE TITLE
Duplicates still occurs when songs under last session is played (I think issue #36 still exists)

### ISSUE THREAD

**Issue by ogbodotg** [Sangwan5688/BlackHole#37] opened 2021-06-10 23:57 UTC
**Describe the bug**
Hi @Sangwan5688 I think this problem #36  still exist when you play songs under "recently played" or "last session". I noticed it creates another duplicate of the particular song played.

**To Reproduce**
1. Go to 'Last Session'
2. Click on ' any song under last session to play'
4. See error 'It creates another copy of the song under 'last session' even though it already existed'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 11]
 - App Version [e.g. v1.5]

**App Logs**
If possible please provide app logs here.

**Comment by Sangwan5688** [comment] 2021-06-12 03:39
Ok, I will check and confirm it.

**Comment by Sangwan5688** [comment] 2021-06-14 12:47
@ogbodotg I can't reproduce the issue. Are you sure the issue still exists. I think there might be some difference between the songs. Just try with any new song. Play it so that it shows up in the list then try playing it again and confirm.

**Comment by Sangwan5688** [comment] 2021-06-17 17:25
I am closing the issue as the issue was already resolved earlier and can't be reproduced. Please make sure that you are using the latest commit. It might also be a case that the two songs are similar, which might have made you think that they are the same.

**Closed by Sangwan5688** 2021-06-17 17:25 UTC
Labels: duplicate
