### ISSUE TITLE
Spotify 

### ISSUE THREAD

**Issue by Hostjio** [Sangwan5688/BlackHole#457] opened 2022-11-28 15:43 UTC
**Describe the bug**

**To Reproduce**
3. Do this and that

**Expected behavior**

**Screenshots**

**Device Details (please complete the following information):**
 - OS: [e.g. Android, Windows, iOS, Linux]
 - Version: [e.g. Android 12, iOS 15, Windows 11 20H2]
![DF442B65-6668-40EF-9C6D-2095187C46E5](https://user-images.githubusercontent.com/106661788/204320032-96930c95-80b7-4945-8e59-2795c5b38452.jpeg)

**App Logs**
If possible please provide app logs here.

**Comment by Sangwan5688** [comment] 2022-12-25 04:18
duplicate of #460

**Closed by Sangwan5688** 2022-12-25 04:18 UTC
Labels: bug
