### ISSUE TITLE
It is taking a lot of tine to load and i'm getting error service unavailable for spotify, but youtube is working fine

### ISSUE THREAD

**Issue by viigneshreddy** [Sangwan5688/BlackHole#369] opened 2022-07-16 09:47 UTC
**Describe the bug**

**To Reproduce**
3. Do this and that

**Expected behavior**

**Screenshots**

**Device Details (please complete the following information):**
 - OS: [e.g. Android, Windows, iOS, Linux]
 - Version: [e.g. Android 12, iOS 15, Windows 11 20H2]
 - Device: [e.g. Pixel 4, iPhone 13]
 - App Version [e.g. v1.13.0]

**App Logs**
If possible please provide app logs here.

**Comment by BrightDV** [comment] 2022-07-16 11:30
Can you please fill the issue template?
Also, if you are not in India, you have to use a VPN with an indian server.

**Comment by viigneshreddy** [comment] 2022-07-16 11:34
I'm from india, yet i face a lot of loading problem and error in service
issue

**Comment by BrightDV** [comment] 2022-07-16 17:49
Can you provide screenshots or, if possible, steps to reproduce your issue?

**Comment by Sangwan5688** [comment] 2022-07-17 07:30
Duplicate of #360, fixed

**Closed by Sangwan5688** 2022-07-17 07:30 UTC
Labels: bug
