### ISSUE TITLE
App is stuck in the splash screen after 2-3 launches

### ISSUE THREAD

**Issue by NeutralDevop** [Sangwan5688/BlackHole#15] opened 2021-05-09 17:14 UTC
The app is crashing and stuck in the splash screen after 2-3 launches in an android 9 device. Correct file of apk was used. The app worked seamlessly in first 2 launches but got this after clearing mobile memory. Clearing the app data resulted in working again. And sometimes the app is not being able to play some of the offline songs and stays in the player. And year data entered in the date of birth section in the settings is not set and is reseted to 2021.And to build the app a Google-services. Json file is asked, providing that would be much of a help. Thank you
![Screenshot_20210509_222956_com shadow blackhole](https://user-images.githubusercontent.com/83843970/117580851-92314a00-b117-11eb-988e-d2205bec7cfc.jpg)
![Screenshot_20210509_224155_com shadow blackhole](https://user-images.githubusercontent.com/83843970/117580929-d1f83180-b117-11eb-9474-0f16f0437a54.jpg)

**Comment by Sangwan5688** [comment] 2021-05-09 19:12
The issue was proposed in #11 also and was resolved as per my knowledge. I haven't released a new version and just modified the apk files to new ones when the issue was resolved. So, if you are using apk published before that then consider downloading again the apk file from releases. Most probably it should be resolved. If not you can open the issue again.

Now coming over the offline play part, I haven't encountered such a problem yet that might be the cause, maybe some error in music or something. So, if you could provide the app log then it will be much helpful.

Finally, about the google-services json file, it contains details like the database name, authorization token, etc which shouldn't be provided publically. What you can do about it is visit firebase and set up things there. They will ask about package name, app name, etc. which you can enter depending upon changes you make to the app or you can enter the current app details. Everything else is already set up in code you just have to download the json file which they will provide.
I will think of something about using a demo json from any other account or something in the future. Or maybe if you could provide one for the repo then you can open a pull request, it will be helpful. Lemme know if you face any issue.

**Comment by NeutralDevop** [comment] 2021-05-10 11:29
You can recreate this scenario by stopping the music through the notification center and then clearing the cache then opening any other app. After these steps, relaunching the app made the app crash and stuck in the splash screen.

**Comment by Sangwan5688** [comment] 2021-05-10 11:48
Still unable to reproduce the issue. Can you reproduce it? And are you able to build the app? Can you provide app logs? As I'm unable to reproduce only app logs can help.

**Comment by NeutralDevop** [comment] 2021-05-10 12:13
I was not able to build the app due to the absence of Google-services.json file. After building the app I will share the app log. This issue appeared after the music being played in the background for around 10 s. And before closing the app a session of playing an offline song then the online song in the background was done.

**Comment by Sangwan5688** [comment] 2021-05-10 12:16
I have already uploaded the google-services.json file. You can try to build and share applog.

**Comment by NeutralDevop** [comment] 2021-05-10 17:13
The build was successful but gave some errors. And the build debug app's home music suggestion were not coming. 
![Screenshot_20210510_224232](https://user-images.githubusercontent.com/83843970/117698245-24e9eb80-b1e1-11eb-80a5-6c7f952a3fa6.jpg)
![Screenshot_20210510_224215](https://user-images.githubusercontent.com/83843970/117698250-26b3af00-b1e1-11eb-8bf6-64c621c8787c.jpg)
![Screenshot_20210510_224130_com whatsapp](https://user-images.githubusercontent.com/83843970/117698255-274c4580-b1e1-11eb-8db8-a3b6a0a6403e.jpg)

**Comment by asifmhdashik** [comment] 2021-05-11 10:10
@Sangwan5688 Hi can you please explain how you did the backend database ,analytics, update notification  configurations for the app in firebase and how can one do their own backend to this app and synchronise .

**Comment by NeutralDevop** [comment] 2021-05-12 10:49
I think the stuck in splash screen problem was solved in version 1.5 because I expirienced this bug only in 1.4 and was unable to recreate it on the emulator. But offline songs listed my music, after 18 songs are not being played and I will share you the log. I can share more. 
![Screenshot_20210512_161642](https://user-images.githubusercontent.com/83843970/117963148-a48ccd00-b33d-11eb-8e56-08aa03f668f2.jpg)
![Screenshot_20210512_161037](https://user-images.githubusercontent.com/83843970/117963156-a6ef2700-b33d-11eb-8d3e-531a1d2a6bdb.jpg)
![Screenshot_20210512_161023](https://user-images.githubusercontent.com/83843970/117963159-a787bd80-b33d-11eb-8317-0e5a5a54988b.jpg)
![Screenshot_20210512_160838_com whatsapp](https://user-images.githubusercontent.com/83843970/117963167-a8205400-b33d-11eb-8712-e8c5d207dffa.jpg)
![Screenshot_20210512_161005](https://user-images.githubusercontent.com/83843970/117963171-a9518100-b33d-11eb-9f61-fd102ae11bc5.jpg)
![Screenshot_20210512_160951](https://user-images.githubusercontent.com/83843970/117963177-aa82ae00-b33d-11eb-87de-9f36a571ef1b.jpg)
![Screenshot_20210512_160936](https://user-images.githubusercontent.com/83843970/117963179-ab1b4480-b33d-11eb-9798-674a56a0d825.jpg)

**Comment by Sangwan5688** [comment] 2021-05-12 11:04
Look like there's something wrong with the 7th song in your "My Music" because of which the loop is breaking and is not reading any other songs after that. Can you look over the 7th songs if there's something special about it like it's missing any name or doesn't have an artist name or something like that. I will also look over the code so that such cases don't cause any issues later on.
The other error was caused because I mistakenly wrote "appVersion" as "double" in the database instead of "string". I have corrected it now.

**Comment by asifmhdashik** [comment] 2021-05-12 11:13
@Sangwan5688 Thank you for sharing .Do I need a specific document ID or can I auto ID it and is there any more changes I need to make in this database.
![Screenshot 2021-05-12 at 4 37 56 PM](https://user-images.githubusercontent.com/76432849/117965782-c8054700-b340-11eb-9a1a-185610d0385a.png)
![Screenshot 2021-05-12 at 4 38 29 PM](https://user-images.githubusercontent.com/76432849/117965800-ccc9fb00-b340-11eb-9b53-56a9f678e8ca.png)

**Comment by Sangwan5688** [comment] 2021-05-12 11:30
@asifmhdashik Do not create "Firebase Database", create "Realtime Database". Then it will automatically generate a name. If you are using the "google-services.json" file of the same firebase then there's no need to edit it. If you want to use your own database then set up a firebase project and they will give a "google-services.json" file. Use that file then when you create a database it will automatically connect to it. No need to change the database name.

**Comment by Sangwan5688** [comment] 2021-05-12 13:04
I am closing this issue as the main issue is already resolved. About the part of not playing some offline music, please mention future comments in #18

**Closed by Sangwan5688** 2021-05-12 13:04 UTC
