### ISSUE TITLE
Android apk vpn errro from india

### ISSUE THREAD

**Issue by rohitrmakwana** [Sangwan5688/BlackHole#334] opened 2022-06-04 02:26 UTC
Latest versions v1.14.0 got error so unable to play any songs from any album what is the resolution?

**Comment by Lokawn** [comment] 2022-06-04 05:29
I am getting the same error.

**Comment by badushaebrahim** [comment] 2022-06-04 05:40
i am get error while trying to connect to server of playlist info

**Comment by Sangwan5688** [comment] 2022-06-04 06:51
Duplicate of #329

**Comment by Sangwan5688** [comment] 2022-06-04 06:51
Servers are up again you can continue playing

**Closed by Sangwan5688** 2022-06-04 06:51 UTC
Labels: bug
