### ISSUE TITLE
Audio Focus

### ISSUE THREAD

**Issue by brnwlshubh** [Sangwan5688/BlackHole#43] opened 2021-06-23 02:33 UTC
In Audio Focus Two or more Android apps can play audio to the same output stream simultaneously.
But Blackhole in this situation becomes mute.
So Please add an option for enable/disable the "Audio Focus"

**Comment by Sangwan5688** [comment] 2021-09-21 14:21
Ya, so in earlier versions of BlackHole, the app used to pause whenever a notification arrives. I don't exactly remember when I fixed the issue but this issue is fixed. What BlackHole does now is that it lowers the audio whenever any other app tries to access audio. As for calls, the paused is paused that time, but can be played even during call after clicking play button once. As the issue is already fixed a long time ago, I will close this now. I completely forgot to mention it before. It has been fixed a long time ago.

**Closed by Sangwan5688** 2021-09-21 14:21 UTC
Labels: enhancement
