### ISSUE TITLE
The buttons are overlapping the text

### ISSUE THREAD

**Issue by GoluLiliput** [Sangwan5688/BlackHole#251] opened 2022-02-09 11:30 UTC
![IMG_20220209_165557.jpg](https://user-images.githubusercontent.com/60719832/153191421-44bd844e-9748-44bc-adfa-c7a3563571af.jpg)

![IMG_20220209_165833.jpg](https://user-images.githubusercontent.com/60719832/153191472-63ebcdd2-c33f-4cf7-875c-e3aa002ca8d5.jpg)

**Comment by Sangwan5688** [comment] 2022-02-09 11:41
Duplicate of #177 & #142
This issue was resolved in [6833d26](https://github.com/Sangwan5688/BlackHole/commit/6833d2654576291d9b6b61f183ad6099a91452a2)

**Closed by Sangwan5688** 2022-02-09 11:41 UTC
Labels: bug
