### ISSUE TITLE
Song Playback is Restarting On unlocking screen after few minutes of Locking

### ISSUE THREAD

**Issue by SachinKarinki** [Sangwan5688/BlackHole#84] opened 2021-07-19 02:03 UTC
Opened an album
Played a song
Locked screen and unlocked in few seconds and song plays fine.
But when i lock the screen and unlock it after 3 or 5 minutes, the song Playback is Restarting that means playing from 0 seconds.

Rom: Lineage OS 18.1
Mobile: Poco X3 Pro

**Comment by Sangwan5688** [comment] 2021-07-19 05:30
Can you tell which one of these is the case?
1. Is this the case when you lock with now playing screen as the main screen and when you unlocked it again, then it opens with now playing screen.
2. Is this the case when you lock mobile with any screen other than now playing screen
3. Or does it happen when the app is in the background and then you lock

**Comment by onlytanmoy** [comment] 2021-07-21 17:57
@Sangwan5688 App in the background with music playing, I lock the screen, unlock it say after circa 4 mins, music still playing but when I tap on BlackHole from notification panel to open the app, current music stops playing and starts from beginning.

**Comment by onlytanmoy** [comment] 2021-07-22 09:15
One more scenario, BlackHole playing in the background and I am browsing Reddit app, after some time if I go to android recent apps section and tap on BlackHole to open it, current playing song stops and starts from beginning.

**Comment by Sangwan5688** [comment] 2021-07-23 03:17
Ya, all these issues were caused by the Image Slider. I have removed the Image Slider as of now. So all these issues are resolved. But you won't be able to slide images now. I might add Image Slider again in the future with all these issues resolved, but as of now and maybe even in the next version. There won't be an Image Slider. You can test the beta version if you want.

**Comment by Sangwan5688** [comment] 2021-07-26 10:26
As told earlier I have removed Image Slider and all these issues are fixed now. So, I'm closing the issue. You can open the Issue again if you feel the issue is not resolved after the Image Slider removal.

**Closed by Sangwan5688** 2021-07-26 10:26 UTC
