### ISSUE TITLE
Error: type '_OneByteString'

### ISSUE THREAD

**Issue by tootbrute** [Sangwan5688/BlackHole#305] opened 2022-05-09 03:33 UTC
**Describe the bug**
Clicking any playlist says ":( Sorry Results Not Found". Sometimes it shows only 1 track on these playlists.

I am in Taiwan if that makes a difference.

Also says:
Error: type '_OneByteString' is not a subset of type 'List<dynamic>' in type cast

**To Reproduce**
1. Click on any playlist.
2. Gives error message or sometimes shows me 1 track on the playlist.

**Expected behavior**
Should show me a playlist of music.

**Screenshots**
Usually this (90% of the time)
![Screenshot_20220508-184106_Trebuchet](https://user-images.githubusercontent.com/47593393/167336127-fc6e43b1-e5ff-468a-98e7-6775e861db83.png)

Occasionally this (10% of the time)
![Screenshot_20220509-113116_Trebuchet](https://user-images.githubusercontent.com/47593393/167336144-2a408f2a-e4bc-4d56-b2f4-20242c39cc4c.png)

**Device Details (please complete the following information):**
 - OS: Android
 - Version: LineageOS 18.1
 - Device: ASUS_X01BDA (Asus ZenFone Max Pro (M2))
 - App Version v1.14.0

**App Logs**
(How to find this?)

**Comment by Sangwan5688** [comment] 2022-05-13 08:27
Duplicate of #282

**Closed by Sangwan5688** 2022-05-13 08:27 UTC
Labels: bug
