### ISSUE TITLE
Only Indian Music

### ISSUE THREAD

**Issue by Xt3ns1s** [Sangwan5688/BlackHole#308] opened 2022-05-10 18:43 UTC
I tried importing a spotify playlist and then the app somehow came up with Indian music in the playlist. I don't listen to Indian music so I'm not sure it would've come up in the imported playlist.

**Comment by Sangwan5688** [comment] 2022-05-12 07:04
Duplicate of #173

**Closed by Sangwan5688** 2022-05-12 07:04 UTC
