### ISSUE TITLE
Cannot Sign in with Spotify

### ISSUE THREAD

**Issue by Am1nCmd** [Sangwan5688/BlackHole#516] opened 2023-02-19 03:01 UTC
**Describe the bug**
Safari cannot open the page because the address is invalid

**Steps To Reproduce**
1. Go to 'Top Chart'
2. Click on 'Sign in to Spotify'

**Expected behavior**
I want to login with spotify

**Screenshots**
![IMG_0845](https://user-images.githubusercontent.com/15339573/219909656-62210110-1bae-4e4b-8f00-bf6df660164f.PNG)

**Device Details (please complete the following information):**
 - OS: iPadOS
 - Version: 15.3.1
 - Device: iPad mini 6
 - App Version v1.15.6

**App Logs:**
I don't know how to share it, by some reason Share Logs cannot be clicked
![IMG_0846](https://user-images.githubusercontent.com/15339573/219909768-9e4498cb-6081-491b-879e-6072391e9c18.PNG)

**Comment by Hex34568** [comment] 2023-02-24 19:12
Same here

**Comment by Sangwan5688** [comment] 2023-03-01 07:52
A Known issue with iOS, will resolve in future releases

**Comment by Sangwan5688** [comment] 2023-03-05 09:15
Fixed in latest commit f247472f6a417b935dca81b72d47d37d2f8f857e

**Closed by Sangwan5688** 2023-03-05 09:15 UTC
Labels: bug

**Comment by Am1nCmd** [comment] 2023-03-05 12:24
Still error using latest release
[cid:7BD42772-0B0A-491C-B7B2-639748208583-L0-001]

Sent from my iPhone

On 5 Mar 2023, at 4.16 PM, Ankit Sangwan ***@***.***> wrote:

﻿

Fixed in latest commit f247472<https://github.com/Sangwan5688/BlackHole/commit/f247472f6a417b935dca81b72d47d37d2f8f857e>

**Comment by Sangwan5688** [comment] 2023-03-05 14:09
It's not released yet, you can try it in the next release.

**Comment by binnichtaktiv** [comment] 2023-03-08 12:46
> It's not released yet, you can try it in the next release.

will the update come this week? Can’t wait🤞🏻

**Comment by Sangwan5688** [comment] 2023-03-08 15:22
> will the update come this week? Can’t wait🤞🏻

Next month most probably

**Comment by anuvindhks** [comment] 2023-05-26 05:57
Same issue with Android, hope the team fixes in the next update, that would be a big improvement because rn I can't even use charts tab

**Comment by Sangwan5688** [comment] 2023-05-26 15:13
@anuvindhks there's no such issue in Android, please make sure you the issue isn't with your spotify account

**Comment by Himanshu1057** [comment] 2023-09-10 13:02
@Sangwan5688 bhai ji...aapke app mei 1.15.6 ke baad sabhi version mei ye dikkat hai..koi bhi song apne app next song pr nhi jata balki baar barr karna pdta hai..up next ke andar jo songs read ho chuke hai vo show hi nhi karta sirf 1 hi song repeat krta hai..ye thik karo aap..or 1.15.6 login issue aa rha hai mai vapis 1.15.6 download kiya to login hi nhi ho rha.kuch kaam hi nhi kar rha  isse aage wale sabhi version mei kaam ho rha hai
